// // auth_service.dart
// import 'package:firebase_auth/firebase_auth.dart';

// class AuthService {
//   final FirebaseAuth _auth = FirebaseAuth.instance;

//   String? verificationId; // Store the verification ID

//   Future<Map<String, dynamic>> signInWithPhoneNumber(String phoneNumber) async {
//     try {
//       final PhoneVerificationCompleted verificationCompleted =
//           (PhoneAuthCredential credential) async {
//         await _auth.signInWithCredential(credential);
//       };

//       final PhoneVerificationFailed verificationFailed =
//           (FirebaseAuthException e) {
//         print('Phone verification failed: ${e.message}');
//       };

//       final PhoneCodeSent codeSent =
//           (String verificationId, int? resendToken) async {
//         // Handle the code sent to the user's phone.
//         print('Verification ID: $verificationId'); // Log the verification ID
//         this.verificationId = verificationId; // Store the verification ID
//       };

//       final PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout =
//           (String verificationId) {
//         // Auto retrieval timeout, e.g., navigate to the code input page.
//       };

//       await _auth.verifyPhoneNumber(
//         phoneNumber: phoneNumber,
//         verificationCompleted: verificationCompleted,
//         verificationFailed: verificationFailed,
//         codeSent: codeSent,
//         codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
//       );

//       return {'success': true, 'message': 'OTP sent successfully'};
//     } catch (e) {
//       print('Error: $e');
//       return {'success': false, 'message': 'Failed to send OTP'};
//     }
//   }

//   Future<User?> verifyOTP(String smsCode) async {
//     try {
//       final AuthCredential credential = PhoneAuthProvider.credential(
//         verificationId: verificationId ?? '',
//         smsCode: smsCode,
//       );

//       final UserCredential userCredential = await _auth.signInWithCredential(credential);
//       return userCredential.user;
//     } catch (e) {
//       print('Error verifying OTP: $e');
//       return null;
//     }
//   }

//   Future<void> signOut() async {
//     await _auth.signOut();
//   }
// }


// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATUNvOJDcK0DhQd1b6GoSTETEp4NrIUiI',
    appId: '1:891802212780:web:48fafaf80755bac3e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    authDomain: 'phone-authentication-1a167.firebaseapp.com',
    storageBucket: 'phone-authentication-1a167.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-SgkomsXAjsGTBOykj9vH8TvzGGDYJqw',
    appId: '1:891802212780:android:bcf47ef6b3065b07e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    storageBucket: 'phone-authentication-1a167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25fvBmcVCcAY5-009Xjqbr_30dDEpmcU',
    appId: '1:891802212780:ios:290d13ed6f4a1984e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    storageBucket: 'phone-authentication-1a167.appspot.com',
    androidClientId: '891802212780-g0j6olcg5aut6hboie2esuk4di4i6u8a.apps.googleusercontent.com',
    iosClientId: '891802212780-ehs00hhu54g7lnk7t3san4po94tffd3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25fvBmcVCcAY5-009Xjqbr_30dDEpmcU',
    appId: '1:891802212780:ios:290d13ed6f4a1984e88209',
    messagingSenderId: '891802212780',
    projectId: 'phone-authentication-1a167',
    storageBucket: 'phone-authentication-1a167.appspot.com',
    androidClientId: '891802212780-g0j6olcg5aut6hboie2esuk4di4i6u8a.apps.googleusercontent.com',
    iosClientId: '891802212780-ehs00hhu54g7lnk7t3san4po94tffd3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );
}